spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456

database:
  backup:
    ## mysql home
    mysql-path: D:\Program Files (x86)\mysql-8.0.26-winx64\bin
    ## mysql 目标host
    target-host: 127.0.0.1
    ## mysql 目标username
    target-username: root
    ## mysql 目标password
    target-password: 123456
    ## 备份时间周期
    schedule-cron: 0 0 12 * * ?
    ## 备份文件保留时间(覆盖替换)
    keep-time:
    ## baklist中的 是排除还是包括
    include: true
    ## 备份列表
    bak-list:
      - fzys
      - uwb
    ## sql保存路径
    file-path: D:\tmp

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
