spring:
  redis:
    host: localhost
    port: 6379
    password: bdtd123
    database: 0

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/realypoint
    username: root
    password: 123456
