spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: bdtd123
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 10
        max-active: 10
        max-wait: 100ms

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/realypoint
    username: root
    password: 123456
