name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: 检出代码
      uses: actions/checkout@v2

    - name: 打印${{ github.ref }}
      run: echo ${{ github.ref }}
